[package]
name = "yarel-test"
version = "0.1.0"
authors = ["Matt Spraggs <matthew.spraggs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yarel = { path = "../yarel" }
crossterm = "*"
regex = "*"
